<?php

namespace Database\Seeders;

use App\Models\Banner;
use App\Models\Category;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\File;

/**
 * Banner + top-level category artwork.
 *
 * The images live IN THE REPO under seeders/data/artwork for the same reason the
 * packshots do: a deploy only ever has what is committed. Ten WebP files, ~0.5 MB.
 *
 * Generated by Codex against the house style (cream ground, emerald and brass
 * packaging, arabesque screen) and deliberately carrying NO lettering of any
 * kind — no Arabic, no Latin, no certification roundel. Invented or garbled
 * script on a halal marketplace would be worse than a plain surface.
 *
 * Idempotent: re-running never piles up media rows.
 */
class ArtworkSeeder extends Seeder
{
    private const ART_DIR = 'seeders/data/artwork';

    /** slug => [file, en, ms] — five top-level categories. */
    private const CATEGORY_ART = [
        'groceries-pantry' => 'category-groceries-pantry.webp',
        'food-snacks' => 'category-food-snacks.webp',
        'drinks' => 'category-drinks.webp',
        'cosmetics-care' => 'category-cosmetics-care.webp',
        'pharma-supplements' => 'category-pharma-supplements.webp',
    ];

    /** Ordered — position drives carousel order. */
    private const BANNERS = [
        ['banner-verified-trade.webp', 'Every seller verified', 'Setiap penjual disahkan', '/certificate-register'],
        ['banner-groceries-pantry.webp', 'Groceries & Pantry', 'Barangan Runcit & Pantri', '/c/groceries-pantry'],
        ['banner-food-snacks.webp', 'Food & Snacks', 'Makanan & Snek', '/c/food-snacks'],
        ['banner-drinks.webp', 'Drinks', 'Minuman', '/c/drinks'],
        ['banner-care.webp', 'Cosmetics & Care', 'Kosmetik & Penjagaan', '/c/cosmetics-care'],
    ];

    public function run(): void
    {
        $this->seedCategories();
        $this->seedBanners();
    }

    private function seedCategories(): void
    {
        $done = 0;

        foreach (self::CATEGORY_ART as $slug => $file) {
            $category = Category::where('slug', $slug)->first();

            if ($category === null) {
                $this->command?->warn("category {$slug} not found — run CategorySeeder first");

                continue;
            }

            if ($this->attach($category, $file, 'image')) {
                $done++;
            }
        }

        $this->command?->info("category artwork: {$done}/".count(self::CATEGORY_ART));
    }

    private function seedBanners(): void
    {
        $done = 0;

        foreach (self::BANNERS as $i => [$file, $en, $ms, $link]) {
            // Keyed on link_url so a re-run updates rather than duplicates.
            $banner = Banner::updateOrCreate(
                ['link_url' => $link],
                [
                    'title' => ['en' => $en, 'ms' => $ms],
                    'position' => $i,
                    'is_active' => true,
                    'starts_at' => null,
                    'ends_at' => null,
                ],
            );

            if ($this->attach($banner, $file, 'image')) {
                $done++;
            }
        }

        // Retire DemoSeeder's imageless placeholders — the grey "HA" slabs that
        // shared the carousel with these. Targeted at that exact link_url rather
        // than "everything else", so a real banner added in the panel survives.
        $retired = Banner::where('link_url', '/search?q=new')->update(['is_active' => false]);

        $this->command?->info("banners: {$done}/".count(self::BANNERS)." (retired {$retired} demo placeholder".($retired === 1 ? '' : 's').')');
    }

    /** @param  \Spatie\MediaLibrary\HasMedia  $model */
    private function attach($model, string $file, string $collection): bool
    {
        $absolute = database_path(self::ART_DIR.'/'.$file);

        if (! File::exists($absolute)) {
            $this->command?->warn("missing artwork {$file}");

            return false;
        }

        // Idempotent on NAME AND SIZE. Name alone is not enough: regenerating the
        // artwork keeps the filename, so a name-only guard would skip the attach
        // and leave the old picture live while reporting success.
        $size = (int) File::size($absolute);

        if ($model->getMedia($collection)->contains(
            fn ($m): bool => $m->file_name === $file && (int) $m->size === $size
        )) {
            return true;
        }

        $model->clearMediaCollection($collection);
        $model->addMedia($absolute)->preservingOriginal()->toMediaCollection($collection);

        return true;
    }
}
